### ISSUE TITLE
VS Build

### ISSUE THREAD

**Issue by BorisKourt** [huycn/zxing-cpp#1]
Hi,

I've been trying to build various `zxing-cpp` forks on Windows and it's been rather difficult. My use case doesn't require encoding, so your current decoder setup should be great. 

Do you have any tips on building this in VS? 

Thank you for starting this new fork, I've used the library from Java and it has been the best of the bunch. 

Best,
Boris

**Comment by huycn** [comment]
Hi,

To build the project with VS, you will need VS2015 (I didn't try VS2013, but it should also work) and CMake (https://cmake.org/).

To build for a traditional desktop application:
1) Open CMake GUI, specify "<path-to-zxing-cpp>\wrappers\gdiplus" as source folder in the first input, specify the build output in the second input, and click on Generate.
2) At prompt, select "Visual Studio 14 2015" (or "Visual Studio 14 2015 Win64" if you want to build for x64 platform); leave the second input (Optional toolset...) empty; leave "Use default native compilers" checked; and click on Finish to generate the VS project. At the end, you will get a solution (.sln) in your binary output directory that you can open in VS. The project ZXingGdiPlus in the solution will generate a static library.

To build as WinRT component (e.g. for used with Windows 10 UWP app):
1) Open CMake GUI, specify "<path-to-zxing-cpp>\wrappers\winrt" as source folder in the first input, specify the build output in the second input, and click on Generate.
2) At prompt, select "Visual Studio 14 2015"; leave the second input (Optional toolset...) empty but change the radio button to "Specify toolchain file for cross-compiling"; and click on Next.
3) In the input of the next dialog, specify the file located at "<path-to-zxing-cpp>\wrappers\winrt\Toolchain-Win10.cmake" and click on Finish to generate the VS project. At the end, you will get a solution (.sln) in your binary output directory that you can open in VS. The project ZXingWinRT will generate a WinRT shared component.
4) This will give you only a .dll file for x86, repeat steps 2) and 3) each time for Win64 and ARM by changing (at step 2) for "Visual Studio 14 2015 Win64" and "Visual Studio 14 2015 ARM" respectively.

Note that the script <path-to-zxing-cpp>\wrappers\winrt\BuildWinCom.bat will automate all the build for WinRT. All you need is make sure that cmake is in your path.

Also, don't forget to look in "test" folder for code sample. The test project itself can be generated using the same procedure above for Windows desktop but with the source as <path-to-zxing-cpp>\test\runners\gdiplus

Good luck!
Huy

**Comment by BorisKourt** [comment]
Thank you for the detailed steps! Will try them out and report back if there are any problems.

Best,
Boris

**Comment by BorisKourt** [comment]
Hi Again, Just gave it a quick test and have a question:

In the instructions here:

```
To build for a traditional desktop application:
1) Open CMake GUI, specify "\wrappers\gdiplus" as source folder in the first input, specify the build output in the second input, and click on Generate.
2) At prompt, select "Visual Studio 14 2015" (or "Visual Studio 14 2015 Win64" if you want to build for x64 platform); leave the second input (Optional toolset...) empty; leave "Use default native compilers" checked; and click on Finish to generate the VS project. At the end, you will get a solution (.sln) in your binary output directory that you can open in VS. The project ZXingGdiPlus in the solution will generate a static library.
```

For step two. If I change the configuration to x64 in VS, it gives me an incompatible architecture error when I try to build. Is there a change to this process if I want a x64 desktop static lib?

Thanks again,
Boris

**Comment by BorisKourt** [comment]
Sorry just realized that I need to select VS Win64 :/ my bad!

**Comment by BorisKourt** [comment]
Just in case another inexperienced-in-visual-studio individual gets stuck on this, if you get:

```
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in App.obj	1	C:\Users\User\App\vc2013\ZXingCore.lib(GenericLuminanceSource.obj)	App		
```
Build the library matching your project setting in (Project -> Properties -> C/C++ -> Code Generation -> Runtime Library) Your project and any libs you use have to match this setting.

My project was `/MTd` but ZXing was built as `/MDd`. I don't really know what the difference is, I just rebuilt ZXing with `/MTd` and everything appears to work. (You can also change your project to match ZXing and therefore avoid rebuilding it.)

Also note (this is getting long!): You will need to match this for all of your build types (x64/Debug/Release etc)

**Comment by huycn** [comment]
Hi Boris,

Thank you for sharing information.
Effectively, the libraries and exe should be built with the same runtime settings.

The difference between /MD and /MT is that the former links C runtime dynamically while the later links it statically. /MD is default and recommended option (see more details here: https://social.msdn.microsoft.com/Forums/en-US/9474efb9-49cd-46e1-8935-ee2bebe95203/difference-in-mt-and-md-run-time-lib-setting?forum=vcgeneral)

That said, if you want to avoid playing with project settings dialogs, open the file zxing-cpp\wrappers\gdiplus\CMakeLists.txt in your text editor and look for the line starting with "add_subdirectory" and insert these two lines BEFORE:
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
and click on Generate in CMake-GUI again to update the project.

Huy

**Comment by BorisKourt** [comment]
Thanks, will take a look!

I am using this with `libcinder` and their template project, so it may be that they chose `/MT` but it could also be me messing something up. I might eventually recompile everything to go with your advice.
