### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by Jaykob** [huycn/zxing-cpp#2]
Could you please provide some build instructions for building with the Android NDK? That would be greatly appreciated!

**Comment by huycn** [comment]
I just update Readme to include build instructions.  Please update and check again.

**Comment by Jaykob** [comment]
Thank you!

**Comment by huycn** [comment]
Thank you, Jaykob, for your contribution!
This is very useful and I'm going to add it to the project. However, I need to create a wrapper for iOS before. The idea is to make the library very simple to use, at least for common use cases.
